In [2]:
import pandas as pd

data = pd.read_csv('data.csv')
data

,Country Name,Country Code,Series Name,Series Code,2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020]
0,Argentina,ARG,Access to electricity (% of population),EG.ELC.ACCS.ZS,9.984958e+01,1.000000e+02,9.998958e+01,1.000000e+02,100
1,Argentina,ARG,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,4.201846e+00,4.071308e+00,3.975772e+00,3.740650e+00,..
2,Argentina,ARG,GDP (constant 2015 US$),NY.GDP.MKTP.KD,5.823766e+11,5.987909e+11,5.831181e+11,5.713045e+11,514772410744.886
3,Brazil,BRA,Access to electricity (% of population),EG.ELC.ACCS.ZS,9.970000e+01,9.980000e+01,9.970000e+01,9.980000e+01,100
4,Brazil,BRA,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2.168575e+00,2.196418e+00,2.071855e+00,2.057811e+00,..
5,Brazil,BRA,GDP (constant 2015 US$),NY.GDP.MKTP.KD,1.743173e+12,1.766233e+12,1.797737e+12,1.819683e+12,1749103394213.21
6,Chile,CHL,Access to electricity (% of population),EG.ELC.ACCS.ZS,1.000000e+02,9.970000e+01,1.000000e+02,1.000000e+02,100
7,Chile,CHL,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,4.749830e+00,4.714020e+00,4.624338e+00,4.821118e+00,..
8,Chile,CHL,GDP (constant 2015 US$),NY.GDP.MKTP.KD,2.467477e+11,2.500978e+11,2.600768e+11,2.620808e+11,246412987238.941
9,Paraguay,PRY,Access to electricity (% of population),EG.ELC.ACCS.ZS,9.840000e+01,9.930000e+01,9.960000e+01,9.970000e+01,100
10,Paraguay,PRY,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,1.059329e+00,1.173720e+00,1.217642e+00,1.165425e+00,..
11,Paraguay,PRY,GDP (constant 2015 US$),NY.GDP.MKTP.KD,3.775688e+10,3.957302e+10,4.084104e+10,4.067692e+10,40343452707.5908
12,Uruguay,URY,Access to electricity (% of population),EG.ELC.ACCS.ZS,9.970000e+01,9.980000e+01,9.980000e+01,9.990000e+01,100
13,Uruguay,URY,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,1.904128e+00,1.774987e+00,1.896042e+00,1.874785e+00,..
14,Uruguay,URY,GDP (constant 2015 US$),NY.GDP.MKTP.KD,5.417453e+10,5.505636e+10,5.531948e+10,5.551334e+10,52115108174.7165
15,Bolivia,BOL,Access to electricity (% of population),EG.ELC.ACCS.ZS,9.180000e+01,9.180000e+01,9.280000e+01,9.508000e+01,97.5541229248047
16,Bolivia,BOL,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,1.995137e+00,2.032547e+00,2.046130e+00,1.940398e+00,..
17,Bolivia,BOL,GDP (constant 2015 US$),NY.GDP.MKTP.KD,3.440730e+10,3.585076e+10,3.736496e+10,3.819323e+10,34855949803.3644
18,Peru,PER,Access to electricity (% of population),EG.ELC.ACCS.ZS,9.420000e+01,9.480000e+01,9.520000e+01,9.555136e+01,99.3118133544922
19,Peru,PER,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,1.838580e+00,1.725909e+00,1.706510e+00,1.745592e+00,..
20,Peru,PER,GDP (constant 2015 US$),NY.GDP.MKTP.KD,1.973089e+11,2.022788e+11,2.103080e+11,2.150202e+11,191469666109.311
21,Ecuador,ECU,Access to electricity (% of population),EG.ELC.ACCS.ZS,9.870000e+01,9.920000e+01,9.870000e+01,9.909000e+01,98.8499984741211
22,Ecuador,ECU,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,2.414027e+00,2.296645e+00,2.349517e+00,2.261470e+00,..
23,Ecuador,ECU,GDP (constant 2015 US$),NY.GDP.MKTP.KD,9.807270e+10,1.003954e+11,1.016898e+11,1.017021e+11,93781977159.7812
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Data from database: Sustainable Development Go...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Last Updated: 07/22/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN